import { PoeMap } from "./App";

/*
Template:
{
  name: "Map Name",
  layout: "Description of the map's layout - cramped/wide open/multiple levels etc.",
  boss: "Description of the map's boss - forced phases/annoying mechanics/damage types etc.",
  cards: ["Array", "of", "card", "names"]
}
*/

export const maps: PoeMap[] = [
  {
    name: "Acid Caverns",
    layout: "Slightly labyrinth-like, mainly long hallways.",
    boss: "2 random Warband bosses",
    cards: ["The Void"],
  },
  { name: "Ancient City", layout: "", boss: "", cards: ["The Damned"] },
  {
    name: "Arachnid Nest",
    layout: "",
    boss: "Spider (Weaver from Act 2)",
    cards: [],
  },
  {
    name: "Arcade",
    layout: "Basically the Marketplace area from act 3.",
    boss: "Twin Ribbons (Herald of Ashes, Herald of Thunder)",
    cards: ["The Poet", "The Saint's Treasure"],
  },
  {
    name: "Arena",
    layout: "Three arenas separated by underground passageways.",
    boss: "Trio from The Grand Arena (act 4)",
    cards: [],
  },
  {
    name: "Arid Lake",
    layout: "Wide open circular-ish map with a central area of water.",
    boss: "Big Rhoa preceeded by 3 Rhoa Nests",
    cards: ["The Tinkerer's Table"],
  },
  {
    name: "Armoury",
    layout:
      "Basically like an indoor room from the Lab, but without traps. Lots of fiddly little rooms.",
    boss: "Discount Gravicius, casts Firestorm",
    cards: ["The Void"],
  },
  {
    name: "Arsenal",
    layout:
      "The Grain Gate area from act 8. Many warehouse-style collections of rooms.",
    boss: "Waves of animated weapons, ending in a big animated weapon.",
    cards: ["Abandoned Wealth", "The Patient"],
  },
  {
    name: "Ashen Wood",
    layout: "Large open area with several small walls.",
    boss: "Bow bandit",
    cards: ["The Scout"],
  },
  {
    name: "Atoll",
    layout: "Pseudo-figure-of-eight version of The Ledge",
    boss: "Big ice totem",
    cards: ["The Catch"],
  },
  {
    name: "Basilica",
    layout: "Long and relatively wide hallways, some LOS breaking geometry.",
    boss: "Innocence - forced phases, super slow.",
    cards: ["The Innocent"],
  },
  {
    name: "Bazaar",
    layout: "Basically the Marketplace area from act 3.",
    boss: "Ancient Sculptor ??? maybe throws traps?",
    cards: ["The Saint's Treasure"],
  },
  {
    name: "Beach",
    layout: "Wide open map, small boss arena.",
    boss: "Hailrake (frosty boy) from Act 1",
    cards: ["The Catch"],
  },
  {
    name: "Belfry",
    layout: "One big circuitous square-ish path.",
    boss: "Act 5 version of Kitava",
    cards: ["The Wrath"],
  },
  {
    name: "Bone Crypt",
    layout: "Lots of small interconnected cramped rooms.",
    boss: "Big Necromancer",
    cards: ["The Wretched"],
  },
  { name: "Bramble Valley", layout: "", boss: "", cards: [] },
  { name: "Burial Chambers", layout: "", boss: "", cards: [] },
  { name: "Cage", layout: "", boss: "", cards: [] },
  { name: "Caldera", layout: "", boss: "", cards: [] },
  {
    name: "Canyon",
    layout: "Wide open layout, not unlike a canyon.",
    boss: "Chicken and dog",
    cards: [],
  },
  { name: "Carcass", layout: "", boss: "", cards: [] },
  { name: "Cells", layout: "", boss: "", cards: [] },
  { name: "Cemetery", layout: "", boss: "", cards: [] },
  { name: "Channel", layout: "", boss: "", cards: [] },
  { name: "City Square", layout: "", boss: "", cards: [] },
  { name: "Cold River", layout: "", boss: "", cards: [] },
  { name: "Colosseum", layout: "", boss: "", cards: [] },
  { name: "Conservatory", layout: "", boss: "", cards: [] },
  { name: "Coral Ruins", layout: "", boss: "", cards: [] },
  {
    name: "Courtyard",
    layout: "Multiple interconnected partially open spaces.",
    boss: "Dominus' lackeys",
    cards: ["The Porcupine", "Peaceful Moments"],
  },
  { name: "Coves", layout: "", boss: "", cards: [] },
  {
    name: "Crimson Temple",
    layout: "Three corridors with perpendicular passages connecting them.",
    boss: "Banshee thing",
    cards: ["The Apothecary"],
  },
  { name: "Crimson Township", layout: "", boss: "", cards: [] },
  { name: "Cursed Crypt", layout: "", boss: "", cards: [] },
  { name: "Dark Forest", layout: "", boss: "", cards: [] },
  { name: "Defiled Cathedral", layout: "", boss: "", cards: [] },
  { name: "Desert Spring", layout: "", boss: "", cards: [] },
  { name: "Dig", layout: "", boss: "", cards: [] },
  { name: "Dry Sea", layout: "", boss: "", cards: [] },
  { name: "Dunes", layout: "", boss: "", cards: [] },
  { name: "Dungeon", layout: "", boss: "", cards: [] },
  { name: "Estuary", layout: "", boss: "", cards: [] },
  { name: "Fields", layout: "", boss: "", cards: [] },
  { name: "Flooded Mine", layout: "", boss: "", cards: [] },
  { name: "Forbidden Woods", layout: "", boss: "", cards: [] },
  { name: "Forking River", layout: "", boss: "", cards: [] },
  { name: "Frozen Cabins", layout: "", boss: "", cards: [] },
  { name: "Gardens", layout: "", boss: "", cards: [] },
  { name: "Ghetto", layout: "", boss: "", cards: [] },
  { name: "Glacier", layout: "", boss: "", cards: [] },
  { name: "Grave Trough", layout: "", boss: "", cards: [] },
  { name: "Graveyard", layout: "", boss: "", cards: [] },
  { name: "Grotto", layout: "", boss: "", cards: [] },
  { name: "Haunted Mansion", layout: "", boss: "", cards: [] },
  { name: "Iceberg", layout: "", boss: "", cards: [] },
  {
    name: "Infested Valley",
    layout:
      "Small area with a bridge connecting to a larger, winding canyon area.",
    boss: "Big chaos bug, gotta kill 3 nests before she spawns. Watch out for chaos degen ground shit.",
    cards: ["Parasitic Passengers"],
  },
  { name: "Ivory Temple", layout: "", boss: "", cards: [] },
  { name: "Jungle Valley", layout: "", boss: "", cards: [] },
  { name: "Laboratory", layout: "", boss: "", cards: [] },
  { name: "Lair", layout: "", boss: "", cards: [] },
  { name: "Lava Chamber", layout: "", boss: "", cards: [] },
  { name: "Lookout", layout: "", boss: "", cards: [] },
  { name: "Malformation", layout: "", boss: "", cards: [] },
  { name: "Marshes", layout: "", boss: "", cards: [] },
  {
    name: "Mausoleum",
    layout: "Figure of eight wide corridor. Kinda like The Ossuary.",
    boss: "Tolman (both phases)",
    cards: [],
  },
  { name: "Maze", layout: "", boss: "", cards: [] },
  { name: "Mesa", layout: "", boss: "", cards: [] },
  { name: "Mineral Pools", layout: "", boss: "", cards: [] },
  {
    name: "Moon Temple",
    layout:
      "Numerous small interconnected square platforms, minimal LOS blocking geometry.",
    boss: "Frosty boy (Moon Orb)",
    cards: ["Wealth and Power"],
  },
  { name: "Museum", layout: "", boss: "", cards: [] },
  {
    name: "Necropolis",
    layout: "Several cramped interconnected rooms.",
    boss: "Big melee skeleton",
    cards: ["The Wretched"],
  },
  { name: "Orchard", layout: "", boss: "", cards: [] },
  { name: "Overgrown Ruin", layout: "", boss: "", cards: [] },
  { name: "Overgrown Shrine", layout: "", boss: "", cards: [] },
  { name: "Palace", layout: "", boss: "", cards: [] },
  { name: "Peninsula", layout: "", boss: "", cards: [] },
  { name: "Phantasmagoria", layout: "", boss: "", cards: [] },
  { name: "Plaza", layout: "", boss: "", cards: [] },
  { name: "Port", layout: "", boss: "", cards: [] },
  { name: "Precinct", layout: "", boss: "", cards: [] },
  {
    name: "Primordial Pool",
    layout: "Wide open circular-ish map with a central area of water.",
    boss: "Malachai (one phase only)",
    cards: [],
  },
  {
    name: "Promenade",
    layout: "Elongated and open split level laneway.",
    boss: "Discount Captain Arteri (Thaumetic Emblem guard) and generic Spark/Lightning Thorns mage.",
    cards: ["The Patient", "The Tinkerer's Table"],
  },
  { name: "Residence", layout: "", boss: "", cards: [] },
  { name: "Shipyard", layout: "", boss: "", cards: [] },
  {
    name: "Shore",
    layout: "Similar to The Coast from Act 1.",
    boss: "Discount Fairgraves",
    cards: ["The Landing"],
  },
  { name: "Shrine", layout: "", boss: "", cards: [] },
  {
    name: "Silo",
    layout: "",
    boss: "",
    cards: ["The Tinkerer's Table", "The Tireless Extractor"],
  },
  {
    name: "Spider Forest",
    layout:
      "Several medium-sized areas connected by tight LOS-breaking pathways.",
    boss: "Discount Alira",
    cards: ["The Doctor", "The Scout"],
  },
  { name: "Stagnation", layout: "", boss: "", cards: [] },
  {
    name: "Strand",
    layout: "Long and winding open pathway",
    boss: "Discount Kraityn and unique guy from South Forest",
    cards: ["The Catch", "The Landing", "The Old Man", "The One That Got Away"],
  },
  {
    name: "Summit",
    layout:
      "Several wide open split-level areas, with an obvious path to the boss arena.",
    boss: "Discount Abberath",
    cards: [],
  },
  {
    name: "Temple",
    layout: "Similar to the leadup area to Piety in Act 3.",
    boss: "Discount Sun Orb guy.",
    cards: ["The Enlightened", "The Twilight Moon", "The Forgotten Treasure"],
  },
  {
    name: "Thicket",
    layout: "Fireflies shit from Act 7.",
    boss: "Big Monke",
    cards: [],
  },
  {
    name: "Tower",
    layout: "Similar to Shavronne's Tower (Act 6)",
    boss: "Discount Brutus and Shavronne",
    cards: ["The Nurse", "The Soul", "The Forward Gaze", "Home"],
  },
  {
    name: "Toxic Sewer",
    layout: "Long, narrow corridors.",
    boss: "Chaos DoT Spider",
    cards: ["The Throne", "The Feast"],
    mechanics: ["blight"],
  },
  {
    name: "Tropical Island",
    layout: "Two elongated open paths separated by a cave.",
    boss: "Big monke",
    cards: ["The Catch", "The Scout"],
    mechanics: ["delirium"],
  },
  {
    name: "Underground River",
    layout: "A single U-shaped corridor.",
    boss: "It That Feel - big dropbear.",
    cards: ["Hunter's Reward"],
  },
  {
    name: "Underground Sea",
    layout: "Similar to The Submerged Passage from Act 1. Many small caves.",
    boss: "Merveil (both phases)",
    cards: ["The Hoarder", "The Tinkerer's Table"],
  },
  {
    name: "Vaal Pyramid",
    layout: "Multiple cramped sections connected by stairs.",
    boss: "Dominus' lackeys",
    cards: ["The Admirer"],
  },
  { name: "Vaal Temple", layout: "", boss: "", cards: [] },
  {
    name: "Vault",
    layout: "Square-shaped circuit with switches to unlock the boss arena.",
    boss: "Robot with safety bubbles.",
    cards: ["The Hoarder"],
  },
  {
    name: "Volcano",
    layout: "Kaom's Dream bullshit.",
    boss: "Kaom Totem",
    cards: ["Pride Before the Fall", "The King's Heart"],
  },
  {
    name: "Waste Pool",
    layout: "Long, narrow corridors.",
    boss: "Sewer Doedre",
    cards: ["The Soul", "The Throne"],
    mechanics: ["blight"],
  },
  {
    name: "Wasteland",
    layout: "Basically the Dried Lake layout.",
    boss: "Discount Voll",
    cards: ["The Void"],
  },
];
