import { PoeMap } from "./App";

/*
Template:
{
  name: "Map Name",
  layout: "Description of the map's layout - cramped/wide open/multiple levels etc.",
  boss: "Description of the map's boss - forced phases/annoying mechanics/damage types etc.",
  cards: ["Array", "of", "card", "names"]
}
*/

export const maps: PoeMap[] = [
  {
    name: "Acid Caverns",
    layout: "Slightly labyrinth-like, mainly long hallways.",
    boss: "2 random Warband bosses",
    cards: ["The Void"],
  },
  { name: "Ancient City", layout: "", boss: "", cards: [] },
  { name: "Arachnid Nest", layout: "", boss: "", cards: [] },
  { name: "Arcade", layout: "", boss: "", cards: [] },
  {
    name: "Arena",
    layout: "Three arenas separated by underground passageways.",
    boss: "Trio from The Grand Arena (act 4)",
    cards: [],
  },
  { name: "Arid Lake", layout: "", boss: "", cards: [] },
  { name: "Armoury", layout: "", boss: "", cards: [] },
  { name: "Arsenal", layout: "", boss: "", cards: [] },
  { name: "Ashen Wood", layout: "", boss: "", cards: [] },
  { name: "Atoll", layout: "", boss: "", cards: [] },
  {
    name: "Basilica",
    layout: "Long and relatively wide hallways, some LOS breaking geometry.",
    boss: "Innocence - forced phases, super slow.",
    cards: ["The Innocent"],
  },
  {
    name: "Bazaar",
    layout: "",
    boss: "",
    cards: [],
  },
  {
    name: "Beach",
    layout: "Wide open map, small boss arena.",
    boss: "Hailrake (frosty boy) from Act 1",
    cards: ["The Catch"],
  },
  { name: "Belfry", layout: "", boss: "", cards: [] },
  {
    name: "Bone Crypt",
    layout: "Lots of small interconnected cramped rooms.",
    boss: "Big Necromancer",
    cards: ["The Wretched"],
  },
  { name: "Bramble Valley", layout: "", boss: "", cards: [] },
  { name: "Burial Chambers", layout: "", boss: "", cards: [] },
  { name: "Cage", layout: "", boss: "", cards: [] },
  { name: "Caldera", layout: "", boss: "", cards: [] },
  {
    name: "Canyon",
    layout: "Wide open layout, not unlike a canyon.",
    boss: "Chicken and dog",
    cards: [],
  },
  { name: "Carcass", layout: "", boss: "", cards: [] },
  { name: "Cells", layout: "", boss: "", cards: [] },
  { name: "Cemetery", layout: "", boss: "", cards: [] },
  { name: "Channel", layout: "", boss: "", cards: [] },
  { name: "City Square", layout: "", boss: "", cards: [] },
  { name: "Cold River", layout: "", boss: "", cards: [] },
  { name: "Colosseum", layout: "", boss: "", cards: [] },
  { name: "Conservatory", layout: "", boss: "", cards: [] },
  { name: "Coral Ruins", layout: "", boss: "", cards: [] },
  {
    name: "Courtyard",
    layout: "Multiple interconnected partially open spaces.",
    boss: "Dominus' lackeys",
    cards: ["The Porcupine", "Peaceful Moments"],
  },
  { name: "Coves", layout: "", boss: "", cards: [] },
  {
    name: "Crimson Temple",
    layout: "Three corridors with perpendicular passages connecting them.",
    boss: "Banshee thing",
    cards: ["The Apothecary"],
  },
  { name: "Crimson Township", layout: "", boss: "", cards: [] },
  { name: "Cursed Crypt", layout: "", boss: "", cards: [] },
  { name: "Dark Forest", layout: "", boss: "", cards: [] },
  { name: "Defiled Cathedral", layout: "", boss: "", cards: [] },
  { name: "Desert Spring", layout: "", boss: "", cards: [] },
  { name: "Dig", layout: "", boss: "", cards: [] },
  { name: "Dry Sea", layout: "", boss: "", cards: [] },
  { name: "Dunes", layout: "", boss: "", cards: [] },
  { name: "Dungeon", layout: "", boss: "", cards: [] },
  { name: "Estuary", layout: "", boss: "", cards: [] },
  { name: "Fields", layout: "", boss: "", cards: [] },
  { name: "Flooded Mine", layout: "", boss: "", cards: [] },
  { name: "Forbidden Woods", layout: "", boss: "", cards: [] },
  { name: "Forking River", layout: "", boss: "", cards: [] },
  { name: "Frozen Cabins", layout: "", boss: "", cards: [] },
  { name: "Gardens", layout: "", boss: "", cards: [] },
  { name: "Ghetto", layout: "", boss: "", cards: [] },
  { name: "Glacier", layout: "", boss: "", cards: [] },
  { name: "Grave Trough", layout: "", boss: "", cards: [] },
  { name: "Graveyard", layout: "", boss: "", cards: [] },
  { name: "Grotto", layout: "", boss: "", cards: [] },
  { name: "Haunted Mansion", layout: "", boss: "", cards: [] },
  { name: "Iceberg", layout: "", boss: "", cards: [] },
  {
    name: "Infested Valley",
    layout:
      "Small area with a bridge connecting to a larger, winding canyon area.",
    boss: "Big chaos bug, gotta kill 3 nests before she spawns. Watch out for chaos degen ground shit.",
    cards: ["Parasitic Passengers"],
  },
  { name: "Ivory Temple", layout: "", boss: "", cards: [] },
  { name: "Jungle Valley", layout: "", boss: "", cards: [] },
  { name: "Laboratory", layout: "", boss: "", cards: [] },
  { name: "Lair", layout: "", boss: "", cards: [] },
  { name: "Lava Chamber", layout: "", boss: "", cards: [] },
  { name: "Lookout", layout: "", boss: "", cards: [] },
  { name: "Malformation", layout: "", boss: "", cards: [] },
  { name: "Marshes", layout: "", boss: "", cards: [] },
  {
    name: "Mausoleum",
    layout: "Figure of eight wide corridor. Kinda like The Ossuary.",
    boss: "Tolman (both phases)",
    cards: [],
  },
  { name: "Maze", layout: "", boss: "", cards: [] },
  { name: "Mesa", layout: "", boss: "", cards: [] },
  { name: "Mineral Pools", layout: "", boss: "", cards: [] },
  {
    name: "Moon Temple",
    layout:
      "Numerous small interconnected square platforms, minimal LOS blocking geometry.",
    boss: "Frosty boy (Moon Orb)",
    cards: ["Wealth and Power"],
  },
  { name: "Museum", layout: "", boss: "", cards: [] },
  {
    name: "Necropolis",
    layout: "Several cramped interconnected rooms.",
    boss: "Big melee skeleton",
    cards: ["The Wretched"],
  },
  { name: "Orchard", layout: "", boss: "", cards: [] },
  { name: "Overgrown Ruin", layout: "", boss: "", cards: [] },
  { name: "Overgrown Shrine", layout: "", boss: "", cards: [] },
  { name: "Palace", layout: "", boss: "", cards: [] },
  { name: "Peninsula", layout: "", boss: "", cards: [] },
  { name: "Phantasmagoria", layout: "", boss: "", cards: [] },
  { name: "Plaza", layout: "", boss: "", cards: [] },
  { name: "Port", layout: "", boss: "", cards: [] },
  { name: "Precinct", layout: "", boss: "", cards: [] },
  {
    name: "Primordial Pool",
    layout: "Wide open circular-ish map with a central area of water.",
    boss: "Malachai (one phase only)",
    cards: [],
  },
  {
    name: "Promenade",
    layout: "Elongated and open split level laneway.",
    boss: "Discount Captain Arteri (Thaumetic Emblem guard) and generic Spark/Lightning Thorns mage.",
    cards: ["The Patient", "The Tinkerer's Table"],
  },
  { name: "Residence", layout: "", boss: "", cards: [] },
  { name: "Shipyard", layout: "", boss: "", cards: [] },
  { name: "Shore", layout: "", boss: "", cards: [] },
  { name: "Shrine", layout: "", boss: "", cards: [] },
  { name: "Silo", layout: "", boss: "", cards: [] },
  { name: "Spider Forest", layout: "", boss: "", cards: [] },
  { name: "Stagnation", layout: "", boss: "", cards: [] },
  {
    name: "Strand",
    layout: "Long and winding open pathway",
    boss: "Discount Kraityn and unique guy from South Forest",
    cards: ["The Catch", "The Landing", "The Old Man", "The One That Got Away"],
  },
  { name: "Summit", layout: "", boss: "", cards: [] },
  { name: "Temple", layout: "", boss: "", cards: [] },
  { name: "Thicket", layout: "", boss: "", cards: [] },
  { name: "Tower", layout: "", boss: "", cards: [] },
  {
    name: "Toxic Sewer",
    layout: "Long, narrow corridors.",
    boss: "Chaos DoT Spider",
    cards: ["The Throne", "The Feast"],
  },
  { name: "Underground River", layout: "", boss: "", cards: [] },
  { name: "Underground Sea", layout: "", boss: "", cards: [] },
  { name: "Vaal Pyramid", layout: "", boss: "", cards: [] },
  { name: "Vaal Temple", layout: "", boss: "", cards: [] },
  { name: "Vault", layout: "", boss: "", cards: [] },
  { name: "Volcano", layout: "", boss: "", cards: [] },
  { name: "Waste Pool", layout: "", boss: "", cards: [] },
  { name: "Wasteland", layout: "", boss: "", cards: [] },
];
